title = "Gitleaks Config"

[extend]
# Use the default config
useDefault = true

[[rules]]
id = "allow-baseline"
description = "Allow .secrets.baseline file"
regex = '''.*'''
path = '''\.secrets\.baseline$'''
tags = ["baseline"]

[allowlist]
paths = [
  '''\.secrets\.baseline$'''
]
